# 1. Import and Install Dependencies

In [5]:
!python -m pip install "tensorflow<2.11" tensorflow tensorflow-gpu

Defaulting to user installation because normal site-packages is not writeable


ERROR: Could not find a version that satisfies the requirement tensorflow<2.11 (from versions: 2.12.0rc0, 2.12.0rc1, 2.12.0, 2.12.1, 2.13.0rc0, 2.13.0rc1, 2.13.0rc2, 2.13.0, 2.13.1, 2.14.0rc0, 2.14.0rc1, 2.14.0, 2.14.1, 2.15.0rc0, 2.15.0rc1, 2.15.0)
ERROR: No matching distribution found for tensorflow<2.11


In [3]:
!pip install  opencv-python mediapipe sklearn matplotlib

Unable to create process using 'C:\Users\FRC 1771\.conda\envs\tf-gpu\python.exe "C:\Users\FRC 1771\.conda\envs\tf-gpu\Scripts\pip-script.py" install  opencv-python mediapipe sklearn matplotlib'


In [2]:
import tensorflow as tf

In [3]:
print(tf.config.list_physical_devices('GPU'))

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


In [ ]:
pip install sklearn

In [1]:
import cv2
import numpy as np
import os
from matplotlib import pyplot as plt
import time
import mediapipe as mp

2024-02-19 12:21:59.537752: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE4.1 SSE4.2, in other operations, rebuild TensorFlow with the appropriate compiler flags.


# 2. Keypoints using MP Holistic

In [2]:
mp_hands = mp.solutions.hands # Holistic model
mp_drawing = mp.solutions.drawing_utils # Drawing utilities
mp_drawing_styles = mp.solutions.drawing_styles

In [3]:
def mediapipe_detection(image, model):
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB) # COLOR CONVERSION BGR 2 RGB
    image.flags.writeable = False                  # Image is no longer writeable
    results = model.process(image)                 # Make prediction
    image.flags.writeable = True                   # Image is now writeable 
    image = cv2.cvtColor(image, cv2.COLOR_RGB2BGR) # COLOR COVERSION RGB 2 BGR
    return image, results

In [4]:
def draw_styled_landmarks(image, results):
    if results:
        if results.multi_hand_landmarks:
            for hand_landmarks in results.multi_hand_landmarks:
                mp_drawing.draw_landmarks(
                    image,
                    hand_landmarks,
                    mp_hands.HAND_CONNECTIONS,
                    mp_drawing_styles.get_default_hand_landmarks_style(),
                    mp_drawing_styles.get_default_hand_connections_style())
        # # Draw face connections
    # mp_drawing.draw_landmarks(image, results.face_landmarks, mp_holistic.FACEMESH_TESSELATION, 
    #                          mp_drawing.DrawingSpec(color=(80,110,10), thickness=1, circle_radius=1), 
    #                          mp_drawing.DrawingSpec(color=(80,256,121), thickness=1, circle_radius=1)
    #                          ) 
    # # Draw pose connections
    # mp_drawing.draw_landmarks(image, results.pose_landmarks, mp_holistic.POSE_CONNECTIONS,
    #                          mp_drawing.DrawingSpec(color=(80,22,10), thickness=2, circle_radius=4), 
    #                          mp_drawing.DrawingSpec(color=(80,44,121), thickness=2, circle_radius=2)
    #                          ) 
    # # Draw left hand connections
    # mp_drawing.draw_landmarks(image, results.left_hand_landmarks, mp_holistic.HAND_CONNECTIONS, 
    #                              mp_drawing.DrawingSpec(color=(121,22,76), thickness=2, circle_radius=4), 
    #                              mp_drawing.DrawingSpec(color=(121,44,250), thickness=2, circle_radius=2)
    #                              ) 
    # # Draw right hand connections  
    # mp_drawing.draw_landmarks(image, results.right_hand_landmarks, mp_holistic.HAND_CONNECTIONS, 
    #                          mp_drawing.DrawingSpec(color=(245,117,66), thickness=2, circle_radius=4), 
    #                          mp_drawing.DrawingSpec(color=(245,66,230), thickness=2, circle_radius=2)
    #                          ) 

In [5]:
WIDTH = 854
HEIGHT = 480
def rescale_frame(frame):
    dim = (WIDTH, HEIGHT)
    return cv2.resize(frame, dim, interpolation =cv2.INTER_AREA)

In [7]:
# import the opencv library 
import cv2 
  
  
# define a video capture object 
    print("running 1")

vid = cv2.VideoCapture(0) 
  
while(True): 
    print("running")
      
    # Capture the video frame 
    # by frame 
    ret, frame = vid.read() 
  
    # Display the resulting frame 
    cv2.imshow('frame', frame) 
      
    # the 'q' button is set as the 
    # quitting button you may use any 
    # desired button of your choice 
    if cv2.waitKey(1) & 0xFF == ord('q'): 
        break
  
# After the loop release the cap object 
vid.release() 
# Destroy all the windows 
cv2.destroyAllWindows() 

IndentationError: unexpected indent (1500414895.py, line 6)

In [41]:
from time import sleep
# cap = cv2.VideoCapture("video.mp4")
cap = cv2.VideoCapture(0)

# cap.set(cv2.CAP_PROP_FOURCC, cv2.VideoWriter_fourcc('Y', 'U', 'Y', 'V')) # depends on fourcc available camera
# cap.set(cv2.CAP_PROP_FRAME_WIDTH, 640)
# cap.set(cv2.CAP_PROP_FRAME_HEIGHT, 480)
# cap.set(cv2.CAP_PROP_FPS, 60)
# Set mediapipe model 

i = 0
results = []

with mp_hands.Hands(model_complexity=0,min_detection_confidence=0.5, min_tracking_confidence=0.5) as hands:
    
    while cap.isOpened():
        
        # Read feed
        ret, frame = cap.read()
        
        # sleep(2)
        
        # i += 1
                
        if ret == True:
            frame = rescale_frame(frame)
            
            # Make detections
            if (i % 2 == 0):
                image, results = mediapipe_detection(frame, hands)
                
                frame = image
            
            
                # print(results.multi_hand_landmarks)

                # image = cv2.resize(image, (640,480))

            # cv2.imshow('OpenCV Feed', frame)
                
                # Draw landmarks
            if cv2.waitKey(5) & 0xFF == ord('p'):
                draw_styled_landmarks(frame, results)

                # Show to screen
            cv2.imshow('OpenCV Feed', frame)
        else:
            print("Out of frames")
            break


        # Break gracefully
        if cv2.waitKey(5) & 0xFF == ord('q'):
            break
    cap.release()
    cv2.destroyAllWindows()

In [17]:
cap.release()
cv2.destroyAllWindows()

In [ ]:
print(results.multi_hand_landmarks)

# 3. Extract Keypoint Values

In [6]:
(extract_keypoints(results))

NameError: name 'extract_keypoints' is not defined

In [32]:
def extract_keypoints(results):
    lh = np.zeros(21*3)
    if (results.multi_hand_landmarks):
        if (results.multi_hand_landmarks[0]):
            # print([[res.x, res.y, res.z] for res in results.multi_hand_landmarks[0].landmark])
            min_x = 9999
            min_y = 9999
            min_z = 9999
            for res in results.multi_hand_landmarks[0].landmark :
                # print(res)
                if (res.x < min_x):
                    min_x = res.x
                if (res.y < min_y):
                    min_y = res.y
                if (res.z < min_z):
                    min_z = res.z
            # print (min_x)
            # print (min_y)
            # print (min_z)
            for res in results.multi_hand_landmarks[0].landmark :
                res.x -= min_x
                res.y -= min_y
                res.z -= min_z
                                           
            lh = np.array([[res.x, res.y, res.z] for res in results.multi_hand_landmarks[0].landmark]).flatten()
            # print(lh)
    rh = np.zeros(21*3)
    if (results.multi_hand_landmarks):
        if (len(results.multi_hand_landmarks) > 1):
            min_x = 9999
            min_y = 9999
            min_z = 9999
            for res in results.multi_hand_landmarks[1].landmark :
                if (res.x < min_x):
                    min_x = res.x
                if (res.y < min_y):
                    min_y = res.y
                if (res.z < min_z):
                    min_z = res.z
            for res in results.multi_hand_landmarks[1].landmark :
                res.x -= min_x
                res.y -= min_y
                res.z -= min_z
            rh = np.array([[res.x, res.y, res.z] for res in results.multi_hand_landmarks[1].landmark]).flatten()
    return np.concatenate([lh, rh])

# 4. Setup Folders for Collection

In [7]:
# Path for exported data, numpy arrays
DATA_PATH = os.path.join('MP_Data') 
TRAINING_PATH = os.path.join('MS-ASL/MS-ASL/videos')

# Actions that we try to detect
# actions = np.array(['hello', 'thanks', 'iloveyou'])
actions = np.array(['eat', 'fish', 'nice', 'milk', 'teacher', 'finish', 'cousin', 'orange', 'yes', 'student', 'sister', 'friend', 'yellow',
                   'white', 'what', 'water', 'want', 'tired', 'pencil', 'mother', 'like', 'drink', 'again', 'table', 'school', 'no', 'help', 'blue', 'spring',
                   'doctor', 'deaf', 'red', 'father', 'black'])

# Thirty videos worth of data
no_sequences = 30

# Videos are going to be 30 frames in length
sequence_length = 30

# Folder start
start_folder = 1

In [3]:
print(actions)

['eat' 'fish' 'nice' 'milk' 'teacher' 'finish' 'cousin' 'orange' 'yes'
 'student' 'sister' 'friend' 'yellow' 'white' 'what' 'water' 'want'
 'tired' 'pencil' 'mother' 'like' 'drink' 'again' 'table' 'school' 'no'
 'help' 'blue' 'spring' 'doctor' 'deaf' 'red' 'father' 'black']


In [ ]:
for action in actions: 
    dir = os.path.join(DATA_PATH, action);
    dirmax = np.max(np.array(os.listdir(dir)).astype(int)) if os.path.exists(dir) else 0
    for sequence in range(1,no_sequences+1):
        try: 
            os.makedirs(os.path.join(DATA_PATH, action, str(dirmax+sequence)))
        except:
            pass

In [ ]:
for action in actions: 
    dir = os.path.join(TRAINING_PATH, action);
    dirmax = np.max(np.array(os.listdir(dir)).astype(int)) if os.path.exists(dir) else 0
    for sequence in range(1,no_sequences+1):
        try: 
            os.makedirs(os.path.join(TRAINING_PATH, action, str(dirmax+sequence)))
        except:
            pass

# 5. Collect Keypoint Values for Training and Testing

In [ ]:
# cap = cv2.VideoCapture(0)

# cap.set(cv2.CAP_PROP_FOURCC, cv2.VideoWriter_fourcc('Y', 'U', 'Y', 'V')) # depends on fourcc available camera
# cap.set(cv2.CAP_PROP_FRAME_WIDTH, 640)
# cap.set(cv2.CAP_PROP_FRAME_HEIGHT, 480)
# cap.set(cv2.CAP_PROP_FPS, 60)
# Set mediapipe model 
with mp_hands.Hands(min_detection_confidence=0.5, min_tracking_confidence=0.5) as hands:
    
    # NEW LOOP
    # Loop through actions
    for action in actions:
        dir = os.path.join(TRAINING_PATH, action)
        # Loop through sequences aka videos
        for sequence in range(start_folder, no_sequences+1):
            dir2 = os.path.join(dir, str(sequence) + ".mp4")
            print(dir2)
            # print(dir)
            cap = cv2.VideoCapture(dir2)
            
            # print(sequence)
            
            # Loop through video length aka sequence length
            frame_num = 0
            
            keypoints = []
            
            while(frame_num < sequence_length):

                # Read feed
                ret, frame = cap.read()
                
                # print(frame_num)
                
                if (ret != True):
                    while (frame_num < sequence_length):
                        frame_num += 1
                        npy_path = os.path.join(DATA_PATH, action, str(sequence), str(frame_num))
                        np.save(npy_path, keypoints)
                    
                    print("Finished!")
                    continue
                
                frame = rescale_frame(frame)
                # Make detections
                image, results = mediapipe_detection(frame, hands)
                
                if (results.multi_hand_landmarks):
                    
                    frame_num += 1

                    # Draw landmarks
                    draw_styled_landmarks(image, results)

                    # NEW Apply wait logic
                    # if frame_num == 0: 
                    #     cv2.putText(image, 'STARTING COLLECTION', (120,200), 
                    #                cv2.FONT_HERSHEY_SIMPLEX, 1, (0,255, 0), 4, cv2.LINE_AA)
                    #     cv2.putText(image, 'Collecting frames for {} Video Number {}'.format(action, sequence), (15,12), 
                    #                cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 255), 1, cv2.LINE_AA)
                    #     # Show to screen
                    #     cv2.imshow('OpenCV Feed', image)
                    #     cv2.waitKey(1500)
                    # else: 
                    cv2.putText(image, 'Collecting frames for {} Video Number {}'.format(action, sequence), (15,12), 
                               cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 255), 1, cv2.LINE_AA)
                    # Show to screen
                    cv2.imshow('OpenCV Feed', image)

                    # NEW Export keypoints
                    keypoints = extract_keypoints(results)
                    npy_path = os.path.join(DATA_PATH, action, str(sequence), str(frame_num))
                    np.save(npy_path, keypoints)
                
                # Break gracefully
                if cv2.waitKey(10) & 0xFF == ord('q'):
                    break
            cap.release()
            cv2.destroyAllWindows()
                    
    cap.release()
    cv2.destroyAllWindows()

In [ ]:
cap.release()
cv2.destroyAllWindows()

# 6. Preprocess Data and Create Labels and Features

In [8]:
from sklearn.model_selection import train_test_split
from tensorflow.keras.utils import to_categorical

In [9]:
label_map = {label:num for num, label in enumerate(actions)}

In [10]:
print(np.load(os.path.join(DATA_PATH, "fish", str(30), "{}.npy".format(2))))

[0.         0.07372111 0.02786348 0.01911409 0.04260802 0.02333661
 0.04519677 0.02271098 0.0198087  0.06500793 0.01091886 0.01641507
 0.07992423 0.         0.01293457 0.04438096 0.03518683 0.01643586
 0.05982426 0.0517444  0.00887192 0.07116848 0.06419826 0.00384299
 0.0786739  0.07364947 0.00048594 0.03923407 0.06256866 0.01440729
 0.05462161 0.10239798 0.00673579 0.06000218 0.12512761 0.00287807
 0.06267467 0.1398083  0.         0.03244993 0.09117419 0.01239146
 0.04551256 0.13053614 0.00378261 0.05208439 0.15226036 0.00264808
 0.05645078 0.1684438  0.00263579 0.02407584 0.11716795 0.0103071
 0.03512727 0.15187222 0.00297833 0.04194069 0.17209792 0.00264455
 0.04676357 0.18928587 0.00345193 0.         0.05991817 0.02198441
 0.01883683 0.0247705  0.01591028 0.04160371 0.01063609 0.01020616
 0.05929461 0.00819993 0.00474914 0.07230619 0.         0.
 0.04760987 0.07233894 0.01147038 0.06071568 0.10323721 0.00692978
 0.05536631 0.09221733 0.00431742 0.04631358 0.07898188 0.0032026
 0.03

In [11]:
sequences, labels = [], []
for action in actions:
    print(action)
    for sequence in range(start_folder, no_sequences + 1):
        window = []
        # dir = os.path.join(DATA_PATH, action, str(sequence))
        # arr = np.array(os.listdir(dir))
        # arr[:] = [s[:-4] for s in arr]
        # dirmax = np.max(arr.astype(int)) if arr.size != 0 else 0
        print(sequence)
        for frame_num in range(1, sequence_length + 1):
            res = np.load(os.path.join(DATA_PATH, action, str(sequence), "{}.npy".format(frame_num)))
            if not (res.any()):
                print(action);
                print(sequence)
            window.append(res)
            # print(frame_num)
        sequences.append(window)
        labels.append(label_map[action])

eat
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
fish
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
nice
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
milk
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
teacher
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
finish
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
cousin
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
orange
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
yes
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
student
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
sister
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
friend
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15

In [10]:
for i in range (1, len(sequences)):
    if (len(sequences[i][1]) != 126):
        print(i);

In [12]:
X = np.array(sequences)
# print(X)

In [13]:
y = to_categorical(labels).astype(int)

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.05)

# 7. Build and Train LSTM Neural Network

In [15]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense
from tensorflow.keras.callbacks import TensorBoard

In [16]:
log_dir = os.path.join('Logs')
tb_callback = TensorBoard(log_dir=log_dir)

In [ ]:
import tensorflow as tf

NUM_PARALLEL_EXEC_UNITS=6

#Assume that the number of cores per socket in the machine is denoted as NUM_PARALLEL_EXEC_UNITS
#  when NUM_PARALLEL_EXEC_UNITS=0 the system chooses appropriate settings 

config = tf.compat.v1.ConfigProto(intra_op_parallelism_threads=NUM_PARALLEL_EXEC_UNITS, 
                        inter_op_parallelism_thrzeads=2, 
                        allow_soft_placement=True,
                        device_count = {'CPU': NUM_PARALLEL_EXEC_UNITS})

session = tf.compat.v1.Session(config=config)

In [14]:
import tensorflow as tf

tf.config.threading.set_intra_op_parallelism_threads(6)
tf.config.threading.set_inter_op_parallelism_threads(2)

In [17]:
model = Sequential()
model.add(LSTM(64, return_sequences=True, activation='relu', input_shape=(np.array(sequences[0]).shape)))
model.add(LSTM(128, return_sequences=True, activation='relu'))
model.add(LSTM(64, return_sequences=False, activation='relu'))
model.add(Dense(64, activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(actions.shape[0], activation='softmax'))

2024-02-19 12:22:37.407032: I tensorflow/core/common_runtime/process_util.cc:146] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.


In [18]:
model.compile(optimizer='Adam', loss='categorical_crossentropy', metrics=['categorical_accuracy'])

In [ ]:
hist = model.fit(X_train, y_train, epochs=10000, callbacks=[tb_callback])

In [ ]:
model.summary()

In [ ]:
fig = plt.figure()
plt.plot(hist.history['loss'], color='teal', label='loss')
plt.plot(hist.history['categorical_accuracy'], color='orange', label='categorical_accuracy')
fig.suptitle('Loss', fontsize=20)
plt.legend(loc="upper left")
plt.xlim(0,1000)
plt.ylim(0,1)
plt.show()

# 8. Make Predictions

In [ ]:
res = model.predict(X_test)

In [ ]:
res

In [ ]:
np.argmax(res[2])|

In [ ]:
actions[np.argmax(res[0])]

In [ ]:
actions[np.argmax(y_test[1])]

# 9. Save Weights

In [ ]:
model.save('msasl1.h5')

In [ ]:
del model

In [19]:
model.load_weights('msasl1.h5')

# 10. Evaluation using Confusion Matrix and Accuracy

In [20]:
from sklearn.metrics import multilabel_confusion_matrix, accuracy_score

In [21]:
yhat = model.predict(X_test)

2/2 [==============================] - 1s 132ms/step


In [22]:
ytrue = np.argmax(y_test, axis=1).tolist()
yhat = np.argmax(yhat, axis=1).tolist()

In [23]:
multilabel_confusion_matrix(ytrue, yhat)

array([[[49,  0],
        [ 0,  2]],

       [[50,  0],
        [ 0,  1]],

       [[48,  0],
        [ 0,  3]],

       [[48,  0],
        [ 0,  3]],

       [[50,  0],
        [ 0,  1]],

       [[49,  0],
        [ 0,  2]],

       [[50,  0],
        [ 0,  1]],

       [[48,  0],
        [ 0,  3]],

       [[50,  0],
        [ 0,  1]],

       [[49,  0],
        [ 0,  2]],

       [[49,  0],
        [ 0,  2]],

       [[50,  0],
        [ 0,  1]],

       [[47,  0],
        [ 0,  4]],

       [[49,  0],
        [ 0,  2]],

       [[47,  0],
        [ 0,  4]],

       [[49,  0],
        [ 0,  2]],

       [[49,  0],
        [ 0,  2]],

       [[50,  0],
        [ 1,  0]],

       [[50,  0],
        [ 0,  1]],

       [[50,  0],
        [ 0,  1]],

       [[49,  0],
        [ 0,  2]],

       [[47,  0],
        [ 0,  4]],

       [[50,  0],
        [ 0,  1]],

       [[49,  0],
        [ 0,  2]],

       [[50,  0],
        [ 0,  1]],

       [[49,  0],
        [ 0,  2]],

       [[50,

In [24]:
accuracy_score(ytrue, yhat)

0.9803921568627451

# 11. Test in Real Time

In [25]:
from scipy import stats

In [26]:
colors = [(245,117,16), (117,245,16), (16,117,245), (16,117,245), (16,117,245)] * 10
def prob_viz(res, actions, input_frame, colors):
    output_frame = input_frame.copy()
    for num, prob in enumerate(res):
        cv2.rectangle(output_frame, (0,60+num*40), (int(prob*100), 90+num*40), colors[num], -1)
        cv2.putText(output_frame, actions[num], (0, 85+num*40), cv2.FONT_HERSHEY_SIMPLEX, 1, (0,0,0), 2, cv2.LINE_AA)
        
    return output_frame

In [49]:
# 1. New detection variables
predictions = []
res = []
sequence = []
threshold = 0.85

import time

predict = True

def predict_word() :
    global res
    while predict :
        time.sleep(0.5)
        if (len(sequence) == sequence_length) :
            res = model.predict(np.expand_dims(sequence, axis=0), verbose=None)[0]
            # print(actions[np.argmax(res)])
            predictions.append(np.argmax(res))
        else:
            res = []

In [51]:
frame = np.zeros(1)
run_cv_thread = True
def run_cv():
    global frame
    cap = cv2.VideoCapture("Validation/Cool/1.mkv")
    ret, frame = cap.read()
    
    while run_cv_thread:
        ret, frame_new = cap.read()
        time.sleep(1 / 15.0)
        if (ret == False):
            break
        frame = frame_new
    cap.release()

In [42]:
frame = np.zeros(1)
run_media = True

def run_mediapipe() :
    with mp_hands.Hands(model_complexity=1, min_detection_confidence=0.5, min_tracking_confidence=0.5) as hands:
    
        global frame
        predictions = []
        res = []
        sentence = []
        frames_wo_points = 0
        while run_media :
            time.sleep(1 / 15.0)
            if (frame.any()):
                frame = rescale_frame(frame)

                # Make detections
                image, results = mediapipe_detection(frame, hands)
                # print(results)

                # Draw landmarks
                draw_styled_landmarks(image, results)

                # 2. Prediction logic
                keypoints = extract_keypoints(results)
#                 if np.any(keypoints):
#                     frames_wo_points = 0
#                     sequence.append(keypoints)
#                     sequence = sequence[-sequence_length:]
#                 else:
#                     frames_wo_points += 1
#                     if (frames_wo_points >= 10):
#                         sequence = []

#                 #3. Viz logic
#                 # print(np.any(predictions) & np.any(res))
#                 if (np.any(predictions) & np.any(res)) :
#                     if np.unique(predictions[-3:])[0]==np.argmax(res): 
#                         # print(res[np.argmax(res)])
#                         # print(np.argmax(res))
#                         if res[np.argmax(res)] > threshold: 
#                             if len(sentence) > 0: 
#                                 if actions[np.argmax(res)] != sentence[-1]:
#                                     sentence.append(actions[np.argmax(res)])
#                             else:
#                                 sentence.append(actions[np.argmax(res)])
#                             # print(sentence)

#                     if len(sentence) > 5: 
#                         sentence = sentence[-5:]


#                     # Viz probabilities
#                     image = prob_viz(res, actions, image, colors)
#                 if (np.any(predictions)):
#                     cv2.rectangle(image, (0,0), (640, 40), (245, 117, 16), -1)
#                     cv2.putText(image, ' '.join(sentence), (3,30), 
#                     cv2.FONT_HERSHEY_SIMPLEX, 1, (255, 255, 255), 2, cv2.LINE_AA)

                # Show to screenP
                cv2.imshow('OpenCV Feed', image)
                
                cv2.waitKey(1)
                # cv2.destroyAllWindows()
                # if cv2.waitKey(10) & 0xFF == ord('q'):
                #     return
    cv2.destroyAllWindows()

In [45]:
print(frame)

[[[186 196 200]
  [186 196 200]
  [190 196 205]
  ...
  [ 60  73  76]
  [ 54  71  75]
  [ 52  69  73]]

 [[185 195 199]
  [185 195 199]
  [188 194 203]
  ...
  [ 60  73  76]
  [ 54  71  75]
  [ 52  69  73]]

 [[191 194 199]
  [191 194 199]
  [192 195 200]
  ...
  [ 56  74  76]
  [ 50  71  75]
  [ 48  69  73]]

 ...

 [[199 214 225]
  [199 214 225]
  [196 213 224]
  ...
  [ 19   9  16]
  [ 25  10  19]
  [ 26  11  20]]

 [[196 213 224]
  [196 213 224]
  [195 212 223]
  ...
  [ 18   8  15]
  [ 21   8  17]
  [ 23  10  19]]

 [[196 213 224]
  [196 213 224]
  [195 212 223]
  ...
  [ 18   8  15]
  [ 21   8  17]
  [ 21   8  17]]]


In [52]:
import threading

t1 = threading.Thread(target=predict_word, args=())
t1.start()
t2 = threading.Thread(target=run_cv, args=())
t2.start()

In [53]:
# dir = os.path.join("MS-ASL/MS-ASL/videos/pencil/1.mp4")
# dir = os.path.join("TRAINING", "hot", "2.mp4")
# cap = cv2.VideoCapture(dir)
# cap = cv2.VideoCapture(0)
       
# cap.set(cv2.CAP_PROP_FOURCC, cv2.VideoWriter_fourcc('Y', 'U', 'Y', 'V')) # depends on fourcc available camera
# cap.set(cv2.CAP_PROP_FRAME_WIDTH, WIDTH)
# cap.set(cv2.CAP_PROP_FRAME_HEIGHT, HEIGHT)
# cap.set(cv2.CAP_PROP_FPS, 60)
# Set mediapipe model 

frames_wo_points = 0

# def run_cv(sequence) :
with mp_hands.Hands(model_complexity=1, min_detection_confidence=0.5, min_tracking_confidence=0.5) as hands:
    predictions = []
    res = []
    sequence = []
    sentence = []
    while (frame.any()):

        frame = rescale_frame(frame)

        # Make detections
        image, results = mediapipe_detection(frame, hands)
        # print(results)

        # Draw landmarks
        draw_styled_landmarks(image, results)

        # 2. Prediction logic
        keypoints = extract_keypoints(results)
        if np.any(keypoints):
            frames_wo_points = 0
            sequence.append(keypoints)
            sequence = sequence[-sequence_length:]
        else:
            frames_wo_points += 1
            if (frames_wo_points >= 10):
                sequence = []

        #3. Viz logic
        # print(np.any(predictions) & np.any(res))
        if (np.any(predictions) & np.any(res)) :
            if np.unique(predictions[-3:])[0]==np.argmax(res): 
                # print(res[np.argmax(res)])
                # print(np.argmax(res))
                if res[np.argmax(res)] > threshold: 
                    if len(sentence) > 0: 
                        if actions[np.argmax(res)] != sentence[-1]:
                            sentence.append(actions[np.argmax(res)])
                    else:
                        sentence.append(actions[np.argmax(res)])
                    # print(sentence)

            if len(sentence) > 5: 
                sentence = sentence[-5:]
            
            
            # Viz probabilities
            image = prob_viz(res, actions, image, colors)
        if (np.any(predictions)):
            cv2.rectangle(image, (0,0), (640, 40), (245, 117, 16), -1)
            cv2.putText(image, ' '.join(sentence), (3,30), 
            cv2.FONT_HERSHEY_SIMPLEX, 1, (255, 255, 255), 2, cv2.LINE_AA)

        # Show to screenP
        cv2.imshow('OpenCV Feed', image)

        # Break gracefully
        if cv2.waitKey(10) & 0xFF == ord('q'):
            break
       
    # cap.release()
    cv2.destroyAllWindows()

In [ ]:
for num, prob in enumerate(res):
    print(num)
    print(prob)
    print((0,60+num*40))
    print((int(prob*100), 90+num*40))
    print(colors[num])

In [47]:
predict = False
t1.join()
predict = True

In [48]:
run_cv_thread = False
t2.join()
run_cv_thread = True

In [37]:
cap.release()
cv2.destroyAllWindows()

NameError: name 'cap' is not defined

In [ ]:
np.unique(predictions[-10:])[0]==np.argmax(res)

In [ ]:
q = np.zeros(1)
run_process = True
run_display = True
def process():
    global q
    cap = cv2.VideoCapture(0)
    ret, frame = cap.read()
    
    while ret & run_process:
        ret, frame = cap.read()
#detection part in my case I use tensorflow then 
     # end of detection part 
        q = frame
    cap.release()

def Display():
    while run_display:
        if q.any():
            frame = q
            cv2.imshow("frame1", frame)
        if cv2.waitKey(1) & 0xFF == ord('q'):
            break
    cv2.destroyAllWindows()

# if __name__ == '__main__':?
#  start threads
p1 = threading.Thread(target=process)
p2 = threading.Thread(target=Display)
p1.start()
p2.start()

In [ ]:
while run_display:
    if q.any():
        frame = q
        cv2.imshow("frame1", frame)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
cv2.destroyAllWindows()

In [ ]:
run_process = False
p1.join()
run_process = True

# 12. Improve Performance using Profiler

In [ ]:
pip install -U tensorboard_plugin_profile

In [ ]:
cap.release

In [ ]:
# def video_to_frames(video_path, size=None):
    # """
    # video_path -> str, path to video.
    # size -> (int, int), width, height.
    # """

cap = cv2.VideoCapture("jQb9NL9_S6U.mp4")


frames = []

while cap.isOpened():
    ret, frame = cap.read()

    if (ret == True):

        frame = rescale_frame(frame)

        cv2.imshow('OpenCV Feed', frame)

            # Break gracefully
    if cv2.waitKey(5) & 0xFF == ord('q'):
        break

cap.release()

# return frames

In [ ]:
video_to_frames("jQb9NL9_S6U.mp4")

In [ ]:
from time import sleep

In [ ]:
    cap.release()
    cv2.destroyAllWindows()

In [42]:
# cap = cv2.VideoCapture("jQb9NL9_S6U.mp4")
cap = cv2.VideoCapture(0)

while cap.isOpened():

    # Read feed
    ret, frame = cap.read()

    # sleep(2)

    # i += 1

    if ret == True:
        frame = rescale_frame(frame)

        # Make detections
#         if (i % 2 == 0):
#             image, results = mediapipe_detection(frame, hands)

#             frame = image


            # print(results.multi_hand_landmarks)

            # image = cv2.resize(image, (640,480))

        # cv2.imshow('OpenCV Feed', frame)

            # Draw landmarks
        # if cv2.waitKey(5) & 0xFF == ord('p'):
        #     draw_styled_landmarks(frame, results)

            # Show to screen
        cv2.imshow('OpenCV Feed', frame)
    else:
        print("Out of frames")
        break


    # Break gracefully
    if cv2.waitKey(5) & 0xFF == ord('q'):
        break
cap.release()
cv2.destroyAllWindows()

In [ ]:
cap.release()
cv2.destroyAllWindows()